## makeCacheMatrix - function maintains a cached copy of 
## the matrix and its inverse
## cacheSolve - function calculates the inverse of the matrix

## Maintains a cached copy of the matrix and its inverse
## Subfunctions:
##  -setMatrix - creates a cached copy of the matrix
##  -getMatrix - returns the cached copy of the matrix
## - setInverse - creates a cached copy of the inverse
## - getInverse - returns the cached copy of the inverse
## Returns a list of all the functions defined in the makeCacheMatrix
## function environment

makeCacheMatrix <- function(x = matrix()) {

    inv <- NULL
    setMatrix <- function(y){
        x <<- y
        inv <<- NULL
    }
    getMatrix <- function() x
    setInverse <- function(y) inv <<- y
    getInverse <- function() inv
    
    list(setInverse = setInverse, getInverse = getInverse,
         setMatrix = setMatrix, getMatrix = getMatrix)
}

## cacheSolve function accepts a list of functions generated by the 
## makeCacheMAtrix function along with the additional arguments 
## required by the solve function.
## 
## Checks for the inverse in the cache. If present then it returns
## the solution, otherwise, it calculates the solution and caches it.
##
## Important: The matrix to be inverted has to be set in the 
## makeCacheMatrix function.
## Returns the inverse of the passed matrix.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    
    retrieved_inv <- x$getInverse()
    if(!is.null(retrieved_inv)) 
        return(retrieved_inv)
    
    inv <- solve(x$getMatrix(), ...)
    x$setInverse(inv)
    inv
}
